import type { ReactElement } from "react";
import Head from "next/head";
import { useQuery } from "react-query";
import { GenreList } from "@/containers/GenreList";
import { ExplorePage } from "@/containers/Explore";
import { PlayList } from "@/containers/PlayList";
import { getCharts, getGenre } from "./api/services";
import { getLayout } from "@/layout/layout";

export default function Explore({ charts, genre }) {
  const { data } = useQuery("charts", getCharts, { initialData: charts });
  return (
    <>
      <Head>
        <title>Deezer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <ExplorePage data={data} />
        <PlayList playlists={data} />
        <GenreList data={genre} />
      </>
    </>
  );
}

Explore.getLayout = getLayout;

export async function getStaticProps() {
  const charts = await getCharts();
  const genre = await getGenre();

  return {
    props: {
      charts: charts,
      genre: genre,
    },
  };
}
